In [4]:
import sys
sys.path.append('../')
import datapot as dp

In [5]:
f = open("../research/nikita/temp.json", 'r')

In [6]:
data = dp.DataPot()
data.fit(f, limit=100)
df = data.transform(f, verbose=True)
df.head(n=10)

fit transformers...
fit transformers...OK
num of new features: 1046

,amount.685,amount.430,amount.161,amount.683,amount.435,amount.371,amount.303,amount.169,amount.203,amount.366,...,amount.710,amount.980,amount.973,amount.448,amount.671,amount.606,amount.170,amount.296,amount.993,amount.938
0,-10841.04,-814.14,-3516.65,224591.58,-11317.39,-15441.57,-11791.06,-7815.79,-1617.06,157214.10,...,-1684.44,NaN,NaN,-6737.75,-25828.03,-2245.92,-3571.68,-4334.62,NaN,NaN
1,NaN,-22459.16,-2582.80,NaN,-17109.39,-8983.66,-2245.92,-23222.54,-65131.56,-22459.16,...,NaN,NaN,NaN,-16871.99,NaN,NaN,-2151.59,-33688.74,NaN,NaN
2,NaN,NaN,-20213.24,NaN,NaN,NaN,NaN,-8983.66,-38180.57,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-2245.92,NaN,NaN,NaN
3,NaN,NaN,-1998.87,NaN,NaN,NaN,-17832.57,-1965.18,-1235.25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-786.07,11229.58,NaN,NaN
4,-17630.44,-8085.30,3368.87,-269.51,-56147.89,-1549.68,-2448.05,-1212.79,-8808.48,-67377.47,...,-224591.58,-10043.29,-16305.35,-943.28,224591.58,-1010.66,-763.61,-2245.92,-3750.68,-4806.26
5,-1706.90,-673774.73,-1805.72,-224591.58,673774.73,-23368.75,-898366.31,-786070.52,-4399.08,-51656.06,...,-2245.92,NaN,NaN,-224591.58,-2288.59,-6872.50,-5300.36,-1122957.89,NaN,NaN
6,67377.47,-11868.77,-16844.37,-5614.79,-25828.03,-842218.41,-381805.68,-39493.98,-426.72,-3368.87,...,-6490.70,NaN,NaN,-10838.12,-7310.46,-3368.87,-14097.61,-31348.49,NaN,-6620.96
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data

DataPot class instance
 - number of features without transformation: 1046
 - number of new features: 1046
features to transform: